blank_issues_enabled: false
contact_links:
  - name: 🤔 Ask a Question
    url: https://github.com/kenboyd-eaton/skills-expand-your-team-with-copilot/discussions
    about: Ask questions about how to use the website or get help
  - name: 📚 Development Guide
    url: https://github.com/kenboyd-eaton/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and develop the application